
package com.synergyj.cursos.webservices.lab11.cliente;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "MuestraContextoServiceImpl", targetNamespace = "http://rpc.sib.webservices.cursos.synergyj.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface MuestraContextoServiceImpl {


    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "muestraContexto", targetNamespace = "http://rpc.sib.webservices.cursos.synergyj.com/", className = "com.synergyj.cursos.webservices.lab11.cliente.MuestraContexto")
    @ResponseWrapper(localName = "muestraContextoResponse", targetNamespace = "http://rpc.sib.webservices.cursos.synergyj.com/", className = "com.synergyj.cursos.webservices.lab11.cliente.MuestraContextoResponse")
    public void muestraContexto(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
