
package com.synergyj.cursos.webservices.lab10.cliente;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebFault(name = "CreditoException", targetNamespace = "http://document.sei.webservices.cursos.synergyj.com/")
public class CreditoException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private CreditoException faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public CreditoException_Exception(String message, CreditoException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public CreditoException_Exception(String message, CreditoException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.synergyj.cursos.webservices.lab10.cliente.CreditoException
     */
    public CreditoException getFaultInfo() {
        return faultInfo;
    }

}
