
package com.synergyj.cursos.webservices.lab10.cliente;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "ValidaCreditoServiceImplService", targetNamespace = "http://document.sib.webservices.cursos.synergyj.com/", wsdlLocation = "http://127.0.0.1:9878/validaCreditoService?wsdl")
public class ValidaCreditoServiceImplService
    extends Service
{

    private final static URL VALIDACREDITOSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.synergyj.cursos.webservices.lab10.cliente.ValidaCreditoServiceImplService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.synergyj.cursos.webservices.lab10.cliente.ValidaCreditoServiceImplService.class.getResource(".");
            url = new URL(baseUrl, "http://127.0.0.1:9878/validaCreditoService?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://127.0.0.1:9878/validaCreditoService?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        VALIDACREDITOSERVICEIMPLSERVICE_WSDL_LOCATION = url;
    }

    public ValidaCreditoServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ValidaCreditoServiceImplService() {
        super(VALIDACREDITOSERVICEIMPLSERVICE_WSDL_LOCATION, new QName("http://document.sib.webservices.cursos.synergyj.com/", "ValidaCreditoServiceImplService"));
    }

    /**
     * 
     * @return
     *     returns ValidaCreditoService
     */
    @WebEndpoint(name = "ValidaCreditoServiceImplPort")
    public ValidaCreditoService getValidaCreditoServiceImplPort() {
        return super.getPort(new QName("http://document.sib.webservices.cursos.synergyj.com/", "ValidaCreditoServiceImplPort"), ValidaCreditoService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ValidaCreditoService
     */
    @WebEndpoint(name = "ValidaCreditoServiceImplPort")
    public ValidaCreditoService getValidaCreditoServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://document.sib.webservices.cursos.synergyj.com/", "ValidaCreditoServiceImplPort"), ValidaCreditoService.class, features);
    }

}
