
package com.synergyj.cursos.webservices.lab10.cliente;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "ValidaCreditoService", targetNamespace = "http://document.sei.webservices.cursos.synergyj.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ValidaCreditoService {


    /**
     * 
     * @param arg0
     * @throws CreditoException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "validaCredito", targetNamespace = "http://document.sei.webservices.cursos.synergyj.com/", className = "com.synergyj.cursos.webservices.lab10.cliente.ValidaCredito")
    @ResponseWrapper(localName = "validaCreditoResponse", targetNamespace = "http://document.sei.webservices.cursos.synergyj.com/", className = "com.synergyj.cursos.webservices.lab10.cliente.ValidaCreditoResponse")
    public void validaCredito(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0)
        throws CreditoException_Exception
    ;

}
