
package com.synergyj.cursos.webservices.lab12.cliente;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "ImageBookSearchService", targetNamespace = "http://document.sei.webservices.cursos.synergyj.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ImageBookSearchService {


    /**
     * 
     * @return
     *     returns java.util.List<com.synergyj.cursos.webservices.lab12.cliente.BookImage>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getWebServiceBooks", targetNamespace = "http://document.sei.webservices.cursos.synergyj.com/", className = "com.synergyj.cursos.webservices.lab12.cliente.GetWebServiceBooks")
    @ResponseWrapper(localName = "getWebServiceBooksResponse", targetNamespace = "http://document.sei.webservices.cursos.synergyj.com/", className = "com.synergyj.cursos.webservices.lab12.cliente.GetWebServiceBooksResponse")
    public List<BookImage> getWebServiceBooks();

}
