
package com.synergyj.cursos.webservices.lab6.cliente;

import java.util.List;
import java.util.concurrent.Future;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.AsyncHandler;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.Response;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "BusquedaLibrosService", targetNamespace = "http://document.sei.webservices.cursos.synergyj.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BusquedaLibrosService {


    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns javax.xml.ws.Response<com.synergyj.cursos.webservices.lab6.cliente.BuscaLibrosResponse>
     */
	//metodo asincrono con response
    @WebMethod(operationName = "buscaLibros")
    @RequestWrapper(localName = "buscaLibros", targetNamespace = "http://document.sei.webservices.cursos.synergyj.com/", className = "com.synergyj.cursos.webservices.lab6.cliente.BuscaLibros")
    @ResponseWrapper(localName = "buscaLibrosResponse", targetNamespace = "http://document.sei.webservices.cursos.synergyj.com/", className = "com.synergyj.cursos.webservices.lab6.cliente.BuscaLibrosResponse")
    public Response<BuscaLibrosResponse> buscaLibrosAsync(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @param asyncHandler
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    //metodo asincrono con future
    @WebMethod(operationName = "buscaLibros")
    @RequestWrapper(localName = "buscaLibros", targetNamespace = "http://document.sei.webservices.cursos.synergyj.com/", className = "com.synergyj.cursos.webservices.lab6.cliente.BuscaLibros")
    @ResponseWrapper(localName = "buscaLibrosResponse", targetNamespace = "http://document.sei.webservices.cursos.synergyj.com/", className = "com.synergyj.cursos.webservices.lab6.cliente.BuscaLibrosResponse")
    public Future<?> buscaLibrosAsync(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "asyncHandler", targetNamespace = "")
        AsyncHandler<BuscaLibrosResponse> asyncHandler);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.util.List<com.synergyj.cursos.webservices.lab6.cliente.Libro>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "buscaLibros", targetNamespace = "http://document.sei.webservices.cursos.synergyj.com/", className = "com.synergyj.cursos.webservices.lab6.cliente.BuscaLibros")
    @ResponseWrapper(localName = "buscaLibrosResponse", targetNamespace = "http://document.sei.webservices.cursos.synergyj.com/", className = "com.synergyj.cursos.webservices.lab6.cliente.BuscaLibrosResponse")
    public List<Libro> buscaLibros(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2);

}
