
package com.synergyj.cursos.webservices.lab6.cliente;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "BusquedaLibrosServiceImplService", targetNamespace = "http://document.sib.webservices.cursos.synergyj.com/", wsdlLocation = "http://127.0.0.1:9879/buscadorLibros?wsdl")
public class BusquedaLibrosServiceImplService
    extends Service
{

    private final static URL BUSQUEDALIBROSSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.synergyj.cursos.webservices.lab6.cliente.BusquedaLibrosServiceImplService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.synergyj.cursos.webservices.lab6.cliente.BusquedaLibrosServiceImplService.class.getResource(".");
            url = new URL(baseUrl, "http://127.0.0.1:9879/buscadorLibros?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://127.0.0.1:9879/buscadorLibros?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        BUSQUEDALIBROSSERVICEIMPLSERVICE_WSDL_LOCATION = url;
    }

    public BusquedaLibrosServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BusquedaLibrosServiceImplService() {
        super(BUSQUEDALIBROSSERVICEIMPLSERVICE_WSDL_LOCATION, new QName("http://document.sib.webservices.cursos.synergyj.com/", "BusquedaLibrosServiceImplService"));
    }

    /**
     * 
     * @return
     *     returns BusquedaLibrosService
     */
    @WebEndpoint(name = "BusquedaLibrosServiceImplPort")
    public BusquedaLibrosService getBusquedaLibrosServiceImplPort() {
        return super.getPort(new QName("http://document.sib.webservices.cursos.synergyj.com/", "BusquedaLibrosServiceImplPort"), BusquedaLibrosService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BusquedaLibrosService
     */
    @WebEndpoint(name = "BusquedaLibrosServiceImplPort")
    public BusquedaLibrosService getBusquedaLibrosServiceImplPort(WebServiceFeature... features) {//features permite al macenas un metodo para respuestas asincoronas
        return super.getPort(new QName("http://document.sib.webservices.cursos.synergyj.com/", "BusquedaLibrosServiceImplPort"), BusquedaLibrosService.class, features);
    }

}
