
package com.synergyj.cursos.webservices.lab9.cliente;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;

import javax.jws.HandlerChain;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "RecepcionInfoServerImplService", targetNamespace = "http://document.sib.webservices.cursos.synergyj.com/", wsdlLocation = "http://127.0.0.1:9878/recepcionInfoServer?wsdl")
@HandlerChain(file = "handlers/cadenaHandlersCliente.xml")
public class RecepcionInfoServerImplService
    extends Service
{

    private final static URL RECEPCIONINFOSERVERIMPLSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.synergyj.cursos.webservices.lab9.cliente.RecepcionInfoServerImplService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.synergyj.cursos.webservices.lab9.cliente.RecepcionInfoServerImplService.class.getResource(".");
            url = new URL(baseUrl, "http://127.0.0.1:9878/recepcionInfoServer?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://127.0.0.1:9878/recepcionInfoServer?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        RECEPCIONINFOSERVERIMPLSERVICE_WSDL_LOCATION = url;
    }

    public RecepcionInfoServerImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RecepcionInfoServerImplService() {
        super(RECEPCIONINFOSERVERIMPLSERVICE_WSDL_LOCATION, new QName("http://document.sib.webservices.cursos.synergyj.com/", "RecepcionInfoServerImplService"));
    }

    /**
     * 
     * @return
     *     returns RecepcionInfoServer
     */
    @WebEndpoint(name = "RecepcionInfoServerImplPort")
    public RecepcionInfoServer getRecepcionInfoServerImplPort() {
        return super.getPort(new QName("http://document.sib.webservices.cursos.synergyj.com/", "RecepcionInfoServerImplPort"), RecepcionInfoServer.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RecepcionInfoServer
     */
    @WebEndpoint(name = "RecepcionInfoServerImplPort")
    public RecepcionInfoServer getRecepcionInfoServerImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://document.sib.webservices.cursos.synergyj.com/", "RecepcionInfoServerImplPort"), RecepcionInfoServer.class, features);
    }

}
